#!/bin/sh

case $1 in
   config)
        cat <<'EOM'
graph_title Ambient humidity
graph_vlabel humidity (%)
graph_category ambient
hum1.label Living Room

EOM
        exit 0;;
esac

printf "hum1.value "
#head -n1 /dev/ttyUSB0 | cut -d "," -f 2
#grep ^1, /dev/ttyUSB0 | cut -d "," -f 2
grep 2, /tmp/433mhz | tail -n1 | cut -d "," -f 3

